### ISSUE TITLE
Copying an instance of Ngl.Resources() passes as reference

### ISSUE THREAD

**Issue by gabriel-abrahao** [NCAR/pyngl#12]
Hi,

I've ran into a curious behaviour when defining a "base" resource variable, for resources shared between different plots in the same script. Take for example:

    resbase = Ngl.Resources() 
    resbase.nglDraw = False 
    res1 = resbase 
    res1.nglFrame = False
    res2 = resbase 
    res2.nglFrame = True

After this, not only `resbase` has a `nglFrame` resource, both it's and `res1`s are `True`, implying perhaps that `Ngl.resources()` are passed as reference instead of copy. 

This is very different from what NCL used to do, and can get very confusing. Is this the intended behaviour? If it is, is there a way to pass it as a copy instead? 

Thanks,
Gabriel

**Comment by rbrownrigg** [comment]
Hi,

I think is more of a python issue/behavior. You might check out:

https://www.geeksforgeeks.org/copy-python-deep-copy-shallow-copy/

Rick

**Comment by gabriel-abrahao** [comment]
Oh, I see, makes sense, thank you! So that's probably why some of the examples make a function to populate each new resource variable with common resources.

For anyone else who runs into the same issue, to assign an actual copy of the resource variable, that won't change anything in the original, just assign a copy.deepcopy() of it instead:

    import copy

    resbase = Ngl.Resources() 
    resbase.nglDraw = False 

    res1 = copy.deepcopy(resbase)
    res1.nglFrame = False
