### ISSUE TITLE
pyngl equivalent to NCL gsnBoxMaximize

### ISSUE THREAD

**Issue by clintrowe** [NCAR/pyngl#16]
I want to convert a process I previously coded in NCL to pyngl.  

I want to create a 4000x2000 png image for a special display. In NCL, since the workspace is always square, I simply create a 4000x4000 image and then crop it with ImageMagick. In order to get the final image to occupy the full space, I use the gsnMaximize and gsnBoxMargin resources in NCL. I can use Ngl.maximize_plot in pyngl to maximize the plot, but I can't seem to get rid of the white space surrounding the plot.

What can I do to get a full 4000 pixel width plot?

**Comment by rbrownrigg** [comment]
Hi Clint,

The most direct answer is "...I don't know". But I'm curious what you mean
by "can't get rid of the white space".  Do you mean the plot does not fill
the 4000**2 along its longest axis (i.e., maximize_plot is not having any
effect)?  Or that imagemagick is unable to trim the resultant image?

Rick

**Comment by clintrowe** [comment]
Hi Rick,

Thanks for the quick answer. I’ll try to clarify and attach some code and plots.  First, what I can do with “traditional” NCL code based on an example. Note that the map plots to the edges of the image (map3_ncl.png)
begin

  wks_type = "png"
  wks_type@wkWidth = 4000/4   ; set to 1000 px for this example
  wks_type@wkHeight = 4000/4
  resname = "map3"
  wks = gsn_open_wks(wks_type,resname)

  ;---Create map
  res                       = True

  res@gsnDraw               = False     ; Don't draw map
  res@gsnFrame              = False     ; Don't advance frame
  res@mpGridAndLimbOn       = False     ; Will add own grid lines
  res@pmTickMarkDisplayMode = "Never"   ; Will add own labels
  res@gsnMaximize           = True
  res@gsnBoxMargin          = 0.0

  map = gsn_map(wks,"CylindricalEquidistant",res)     ; Won't get drawn just yet

  draw(map)
  frame(wks)

  end

Now, if I convert that code to pyngl and run it, the resulting plot doesn’t go to the edges (map3_pyngl.png) [Note my feeble attempt to set a BoxMargin resource, which resulted in “_set_spc_res: Unknown special resource nglBoxMargin”, but had no effect on the resulting image]
import numpy as np
import Ngl

wks_type = "png"
resname = "map3"
reslist = Ngl.Resources()
reslist.wkWidth = 4000/4
reslist.wkHeight = 4000/4
wks = Ngl.open_wks(wks_type,resname,reslist)

#---Create map
res                       = Ngl.Resources()

res.nglDraw               = False     # Don't draw map
res.nglFrame              = False     # Don't advance frame
res.mpGridAndLimbOn       = False     # Will add own grid lines
res.pmTickMarkDisplayMode = "Never"   # Will add own labels
res.nglBoxMargin          = 0.0

map = Ngl.map(wks,res)     # Won't get drawn just yet

#---Resize plot and draw
Ngl.maximize_plot(wks,map)

Ngl.draw(map)
Ngl.frame(wks)

Ngl.end()

With the image from NCL, I can easily crop it to the desired 4000x2000 using ImageMagick, but with the pyngl plot, it would require some effort – making the plot a little larger to start (but how much larger), then cropping white space from all four sides.

The reason behind all this is that we recently installed a spherical display system in our state history museum and I want to create some visualizations for it and the starting point for images is a 4000x2000 lat-lon map. I’ve had success using Unidata’s Gempak to do this with NWS forecast data (converted from grib2) but want to do this with netCDF files from GCMs. I wanted to avoid the pains of trying to convert from netCDF to gempak format and just use pyngl, as I could also do the necessary cropping and compositing in python, using an image processing library (e,g,, Pillow or pgmagick).

Thanks,
Clint

========================================================
Clinton M. Rowe
Professor and Graduate Chair         phone:(402)472-1946
Earth & Atmospheric Sciences           fax:(402)472-4917
University of Nebraska- Lincoln           crowe1@unl.edu<mailto:crowe1@unl.edu>

**Comment by clintrowe** [comment]
I'm not sure if the images got through (I'm not an experienced Github poster), so I've pasted them here.

![map3_ncl](https://user-images.githubusercontent.com/24945324/59864873-59ceca00-934d-11e9-8c31-e03de62ea724.png)

![map3_pyngl](https://user-images.githubusercontent.com/24945324/59864885-5f2c1480-934d-11e9-9c58-3a995de8df4d.png)

**Comment by clintrowe** [comment]
Oops!

**Comment by rbrownrigg** [comment]
Hmmm...this seems to be a built in behavior. There's this from the docs
(note the special resource nglMaximize vs. the NCL-style "maximize_plot").
I tried setting nglPaperMargin = 0. to no effect.

*nglMaximize* If set to True (the default), then the plot drawn will be
maximized in the workstation on which it is being drawn. For an X11 window
or an NCGM file, this means the plot will be expanded to fill the biggest
possible space within a square, with a small margin around all edges. The
aspect ratio will be preserved. For a PostScript or PDF file, the plot will
be expanded to fill the biggest possible space on an 8 1/2" x 11" sheet of
paper. You can change the default orientation with the resource
*nglPaperOrientation*
<https://www.pyngl.ucar.edu/Resources/ngl.shtml#nglPaperOrientation>.

Note: if you are setting the *vpWidthF*
<http://www.ncl.ucar.edu/Document/Graphics/Resources/vp.shtml#vpWidthF> or
*vpHeightF*
<http://www.ncl.ucar.edu/Document/Graphics/Resources/vp.shtml#vpHeightF>
resources, then you should set *nglMaximize*
<https://www.pyngl.ucar.edu/Resources/ngl.shtml#nglMaximize> to False, as
this resource will cause these two resource values to be recalculated.

Default: True

**Comment by clintrowe** [comment]
Thanks, Rick!  I removed the call to Ngl.maximize_plot and added the following resources before the Ngl.map and it now maps to the edges

res.vpXF = 0.0
res.vpYF = 1.0
res.vpWidthF = 1.0
res.vpHeightF = 1.0
res.nglMaximize = False

![map3_pyngl-2](https://user-images.githubusercontent.com/24945324/59866747-f4310c80-9351-11e9-9644-e90bdefc36f1.png)
