### ISSUE TITLE
python 3 development snapshot?

### ISSUE THREAD

**Issue by Meteodan** [NCAR/pyngl#2]
In a similar vein to https://github.com/NCAR/pynio/issues/17, I was wondering if a development snapshot of a python 3-compatible version of pyngl was in the works? I'm in the process of making the move to python 3, and have some code that I inherited that uses pyngl for plotting soundings that I'd like to be able to port over.

Thanks for any info you can give!

**Comment by khallock** [comment]
Hi @Meteodan, I have actually been working on adding Python 3 support to PyNGL over the last few weeks. There is one remaining bug to deal with before releasing a beta, but this should hopefully happen in the near future. I'll be sure to post an update on this thread once the "dev snapshot" is released.

**Comment by EOSIT** [comment]
The https://www.pyngl.ucar.edu/Download/ page says _"PyNGL will be available for Python 3.x the week of August 20-24, 2018."_  - is this still the case?

**Comment by marylhaley** [comment]
Yes, we are running PyNGL through the required testing for incorporation
into conda and we hope for this to be done early the week of August 20-24.

**Comment by marylhaley** [comment]
PyNGL has been available for Python 3 since August 21, 2018.
