### ISSUE TITLE
Reusing the interpreter after Ngl.end()

### ISSUE THREAD

**Issue by gabriel-abrahao** [NCAR/pyngl#24]
Hello all,

I generally use python on a jupyter notebook in Atom. In that context, it
would be useful to rerun just the plotting part of a script when iterating
with resources and such. However, after calling `Ngl.end()` apparently something is
flushed/closed and you can't open a workspace again.

Is there something one can do after `Ngl.end()` to make the Ngl stuff work
again, short of restarting the kernel/interpreter and losing everything
else the script did? I supposed that would also be useful for creating plots inside a reusable function and similar applications.

Thank you,

**Comment by KMFleischer** [comment]
Hi Gabriel,

I think you shouldn't use the **Ngl.end()** function in notebooks when you want to close and open multiple workstations. 

To close the workstation use **Ngl.delete_wks(wks)**. The graphic output files like PDF or PS will be closed savely. Then you can open a new workstation to proceed as normal.

Also you can open several workstations and use the function **Ngl.change_workstation(plot, wks)** to switch between these workstations. 

See also http://www.pyngl.ucar.edu/Functions/workstation.shtml

-Karin

**Comment by gabriel-abrahao** [comment]
Sorry for the late reply but thanks, worked like a charm!
