### ISSUE TITLE
ModuleNotFoundError foy PyNIO and PyNGL

### ISSUE THREAD

**Issue by katherbreen** [NCAR/pyngl#38]
I'm trying to get started with PyNIO and PyNGL, and I'm having issues getting the packages to import once I've activated the environment. I'm a Linux user on CentOS 7 with Anaconda 4.8.5 installed. I was able to install the packages into a new environment as shown on the main page, but when I try to import the packages I get a ModuleNotFoundError return. Once the environment is activated, I can import common packages like Numpy without issue, but I'm unable to import both PyNIO and PyNGL. I have not installed other packages into the environment, and the source for all packages is conda-forge. I am using the following import commands:

import Nio
import Ngl

**Comment by jepn** [comment]
I have the issues on my mack 
Installed Pyngl and pynio into a new environment as recommended 
Can import the ngl
but get the following error when import nio
ImportError: dlopen(/Users/jesper_nissen/opt/anaconda3/envs/pynio/lib/python3.8/site-packages/PyNIO/_nio.cpython-38-darwin.so, 2): Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Users/jesper_nissen/opt/anaconda3/envs/pynio/lib/libtiledb.dylib
  Reason: image not found

**Comment by erogluorhan** [comment]
Hi,

@katherbreen Sorry for late reply! @jepn , thanks for your comments!

I am sorry for the inconveniences you had or are having with PyNIO and PyNGL. Before moving forward with these two packages, I would first like to let you know both of these packages are in maintenance mode and will no longer be actively developed. Please see [GeoCAT November 2020 Community Update](https://geocat.ucar.edu/blog/2020/11/11/November-2020-update) to see details about this announcement. 

Please let me know if you need help with the replacement packages (i.e. GeoCAT-examples for PyNGL, Xarray and so for PyNIO) after reading the above community update.

Best,

Orhan - GeoCAT

**Comment by buhion** [comment]
@katherbreen ,
`conda install tbb=2020.2` solved this for me

**Comment by Xiaoxu-Tian** [comment]
I've encountered the same problem and installing any tbb but tbb=2020.2 doesn't solve the issue. Please consider adding the necessary tbb into the dependency.

> @katherbreen , `conda install tbb=2020.2` solved this for me
