### ISSUE TITLE
Raise warning 'tmEqualizeXYSizes ' when plotting wrfout file

### ISSUE THREAD

**Issue by muchojp** [NCAR/pyngl#40]
When I was plotting my wrfout file by using an example program: wrf1.py on PyNGL website (https://www.pyngl.ucar.edu/Examples/Scripts/wrf1.py),   I encountered the warning: 'warning:tmEqualizeXYSizes is not a valid resource in contour.PlotManager at this time'.   

I think this warning appears when I get lon and lat from wrfout file and set them to sfXArray and sfYArray. (This is not sure but seems true.)  

Judging from ncl-talk, this problem seems not to be fixed for a long time.   

The best choice is to fix it, but I can't.  So, I want to avoid this warning by setting like 'warning verbose = False'.   

Is There any setting like 'verbose = False' in PyNGL or other methods avoid tmEqualizeXYSizes warning?
Give me some idea, ty :)

**Comment by erogluorhan** [comment]
Hi @muchojp ,

I am sorry for the inconvenience. Before diving deeper with the PyNGL issue, I'd like to inform you that you can find our latest community update about PyNGL's current "maintenance mode" status and our growing [GeoCAT plotting gallery](https://geocat-examples.readthedocs.io/en/latest/index.html) here: [GeoCAT November 2020 Update](https://geocat.ucar.edu/blog/2020/11/11/November-2020-update) and [NCL open letter](http://ncl.ucar.edu/Document/Pivot_to_Python/september_2019_update.shtml).

After referring to the above announcement, you may find a walk-around through our existing [GeoCAT plotting gallery](https://geocat-examples.readthedocs.io/en/latest/index.html) examples for your `wrf1` work or you may find it useful to add it into our [GeoCAT plotting gallery](https://geocat-examples.readthedocs.io/en/latest/index.html) stack. We also welcome community contribution to our open development efforts.

I hope it'd be helpful.

Orhan @ GeoCAT

**Comment by muchojp** [comment]
@erogluorhan 
Thanks for replying. And, sorry for my late response.

I didn't know that PyNGL is in "maintenance mode" status.  And also I didn't know about GeoCAT. 

For Python users, geocat-viz is easier to plot than PyNGL in interface and grammar because geocat-viz uses Matplotlib which is the most used plotting module in Python. "geocat-viz" will be useful especially for young researchers and students who are Python native.  I appreciate you and your team. 

One thing I want you to do if you have authorization on t[he PyNGL webpage](https://www.pyngl.ucar.edu/index.shtml) is to change a hyperlink destination of [Letter to NCL users](http://www.ncl.ucar.edu/open_letter_to_ncl_users.shtml) to the latest version of [letter](http://www.ncl.ucar.edu/Document/Pivot_to_Python/september_2019_update.shtml) in order for PyNGL user to notice the latest status of PyNGL. 

Thank you. 

muchojp

**Comment by erogluorhan** [comment]
Hi @muchojp 

Thanks a lot for your feedback, that is very helpful for us!

I agree that we should update the hyperlink in the PyNGL webpage to our latest letter; we will do this asap.

I'd like to give some clarification on [GeoCAT-viz](https://github.com/NCAR/geocat-viz), or more in general about [GeoCAT gallery](https://geocat-examples.readthedocs.io/en/latest/). The whole gallery functionality has been implemented (and still growing fast) at a Github repository called [GeoCAT-examples](https://github.com/NCAR/GeoCAT-examples), where plotting capabilities and projections are mostly handled by `matplotlib` and `cartopy`. The [GeoCAT-viz](https://github.com/NCAR/geocat-viz) repository, in addition, is not a stand alone codebase; instead, it contains tools to help plot data, primarily convenience functions that are used to facilitate plotting geosciences data with `matplotlib`, `cartopy`, and possibly other Python ecosystem plotting packages, in a higher level implementation aproach. That said, [GeoCAT-viz](https://github.com/NCAR/geocat-viz) functionality is mainly used by [GeoCAT-examples](https://github.com/NCAR/GeoCAT-examples) repository and is of possible use for other GeoCAT components.

I hope this is helpful for your potential future use and contribution.

Please let me know if we can close this issue then.

Best,

Orhan @ GeoCAT

**Comment by muchojp** [comment]
Hi @erogluorhan 

I appreciate your contribution to the Geocat project. 

It is no problem to close this issue. 

Thank you. 

muchojp
