### ISSUE TITLE
Contour Plot with Latitude on the X-Axis

### ISSUE THREAD

**Issue by jasonltorchinsky** [NCAR/pyngl#44]
I am currently attempting to recreate some of the figures of [this paper](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019MS001863), in particular the first part of Figure 5. This plot shows the zonally-averaged zonal wind-speed at various latitudes (horizontal axis) and vertical axis (altitude, in pressure).

With regard to software version and installation, I have the latest version of PyNGL and have successfully run several of the example codes found on the [PyNGL website](https://www.pyngl.ucar.edu/Examples/gallery.shtml).

Unfortunately, the data file I am using is too large to include here, so I will only be able to attached the script. If the data file would also be helpful, I can probably put it on Google Drive and include a link.

Most of the script is processing the data which is output by the atmospheric component of the [E3SM](https://e3sm.org/). After the processing, I have three arrays:
- A 1-D array of latitudes in ascending order, which I shall call `uniqueLatitudes` (as it is in the script). It is of shape `(5651,)`.
- A 1-D array of altitudes in ascending order, which I shall call `lev` (as it is in the script). It is of shape `(72,).
- A 2-D array of zonally-averaged zonal-wind speeds, which I shall call `sortedZonalMeans` (as it is in the script). It is of shape `(72, 5651)`.

I am attempting to make a contour plot of `sortedZonalMeans` with `lev` on the vertical axis and `uniqueLatitudes` on the horizontal axis. To do this, I tried to follow the example of `irregular.py` (found on the [PyNGL website](https://www.pyngl.ucar.edu/Examples/gallery.shtml)) and so the plotting part of the code is:

```
# Set up the plot
wks_type = "png"
wks = Ngl.open_wks(wks_type,"zonal_3Y")

cnres                 = Ngl.Resources()

# Plot title
cnres.tiMainString        = "3-Year Climatology of Zonal Wind (Zonally-Averaged)"
cnres.tiMainFontHeightF   = 0.02

# Scalar field resources
cnres.sfXArray        = uniqueLatitudes
cnres.sfYArray        = lev

contour = Ngl.contour(wks,sortedZonalMeans,cnres)
```

Running the entire Python script with the necessary data files, I obtain the error message:
```
warning:_NhlCreateSplineCoordApprox: Attempt to create spline approximation for X axis failed: consider adjusting trXTensionF value
warning:IrTransInitialize: error creating spline approximation for trXCoordPoints; defaulting to linear
```
Following the advice of these error messages and the [documentation](https://www.ncl.ucar.edu/Document/Graphics/Resources/tr.shtml), I tried adjusting the `trXTensionF` value

```
# Set up the plot
wks_type = "png"
wks = Ngl.open_wks(wks_type,"zonal_3Y")

cnres                 = Ngl.Resources()

# Plot title
cnres.tiMainString        = "3-Year Climatology of Zonal Wind (Zonally-Averaged)"
cnres.tiMainFontHeightF   = 0.02

# Scalar field resources
cnres.sfXArray        = uniqueLatitudes
cnres.sfYArray        = lev
cnres.trXtensionF   = 0.1

contour = Ngl.contour(wks,sortedZonalMeans,cnres)
```
which didn't change the error messages.

**Hypothesis 1:** I think this issue is from the non-linearity of the latitudes in the `uniqueLatitudes` array, as shown in this `ListPlot` generated with Mathematica

![image](https://user-images.githubusercontent.com/46936542/106807345-a94f3000-662e-11eb-88fb-54d2acf0346a.png)

I don't know how to resolve this issue if this is the cause.

**Hypothesis 2:** Another possible issue might be with the precision of the latitudes in `uniqueLatitudes`. The original latitudes array gives the latitude of each column of air that is simulated, meaning that many latitudes are repeated in the original latitudes list. I use a `dict` to create a list of key-value pairs where the key is a latitude and the value is a list of indices of the original latitudes lists corresponding to that latitude.

I think the precision of the latitudes in the key of `uniqueLatitudes` may be greater than when it is used as the `sfXArray`, such that the `sfXArray` has duplicate entries. (I just thought of this, so I will work to amend that issue in the creation of `uniqueLatitudes`).

UPDATE: I don't believe the issue is **Hypothesis 2**, I tried rounding all of the latitudes to the nearest hundredth, tenth, and integer and received the same error.

Any ideas for resolving this?

[clim_zonal.py.txt](https://github.com/NCAR/pyngl/files/5921304/clim_zonal.py.txt)

**Comment by erogluorhan** [comment]
Hi @jasoncunning 

Thank you for your message and sorry to hear the inconvenience you are currently having!

I am happy to help you out using our toolkits. However, I'd like to first emphasize PyNGL is currently in maintenance mode (i.e. no active development, no code or new implementation support, and only critical bug fixes for existing users), and we have been developing [GeoCAT-examples](https://geocat-examples.readthedocs.io/en/latest/) that is based on modern Python ecosystem instead. You can see further details about these decisions in our [November 2020 Community Update](https://geocat.ucar.edu/blog/2020/11/11/November-2020-update).

So, I'd kindly suggest that you have a look at GeoCAT-examples and its [Github repository](https://github.com/NCAR/GeoCAT-examples) as it has more than 100 plotting examples including several contour plots. If you do so, please let us know if you have any issue using any of our GeoCAT-examples scripts to replicate the plots in the paper you mentioned. We'd be happy to help you out for our existing codes or even implementing new scripts if there is a benefit for community.

Hope this helps a bit. Best,

Orhan - GeoCAT

**Comment by jasonltorchinsky** [comment]
Hi @erogluorhan,

Thank you so much for the recommendation! I will happily take a look at GeoCAT, I really appreciate the information. I'll close this issue.

Best,

Jason
