### ISSUE TITLE
Missing example netCDF Files in Tutorials 

### ISSUE THREAD

**Issue by jMichaelA** [NCAR/pyngl#47]
I'm following the PyNGL tutorials and I can't find the netCDF files found in the tutorials.

Example 2 for contour plots (https://www.pyngl.ucar.edu/Tutorial/ngl02p.shtml):
runs:
`cdf_file = Nio.open_file(Ngl.pynglpath("data") + "/cdf/contour.cdf","r")`

I can't find anywhere where I can download contour.cdf

Same thing for the rest of the example files. Could those be added or made available for download somewhere?

**Comment by KMFleischer** [comment]
Hi,

you can retrieve the path with the short script

import Ngl
import os

print(os.path.join(Ngl.pynglpath("data"),"cdf","contour.cdf"))


The result should be the same as

ls $NCARG_ROOT/lib/python3.8/site-packages/ngl/ncarg/data/cdf/contour.cdf

-Karin


Am 17.06.21 um 23:50 schrieb jMichaelA:

**Comment by jMichaelA** [comment]
Thanks @KMFleischer I didn't realize the tutorial data files came with the package.
