### ISSUE TITLE
Is it possible to convert colormaps to be used in matplotlib?

### ISSUE THREAD

**Issue by guidocioni** [NCAR/pyngl#53]
Although pyngl is in maintenance mode since years I still have installed because of some functionalities that I couldn't find anywhere else (like `natgrid`).

Another feature that I would like to port are the colormaps.

Is it possible to get a colormap defined in `pyngl` and convert it to one that `matplotlib` understands?

**Comment by guidocioni** [comment]
It was as easy as 

```python
import Ngl
cmap = colors.ListedColormap(Ngl.read_colormap_file(cmap_name),
                             name=cmap_name)
```

**Comment by erogluorhan** [comment]
Thanks very much, @guidocioni !
