### ISSUE TITLE
ilapsf feature request

### ISSUE THREAD

**Issue by adriantompkins** [NCAR/pyngl#56]
This is a request to ask if a wrapper can be added for the function [ilapsf](https://www.ncl.ucar.edu/Document/Functions/Built-in/ilapsF-1.shtml) for the inverse Laplacian operator that was such a useful feature of ncl. There doesn't seem to be any package in python that offers an equivalent function at the moment.

**Comment by kafitzgerald** [comment]
Thanks for the feature request!

This project is [currently in maintenance mode](https://geocat.ucar.edu/blog/2020/11/11/November-2020-update), but the functionality you mentioned would potentially be a nice addition to [geocat-comp](https://github.com/NCAR/geocat-comp).  I'll link to this from over there and we'll take a look.   

If you have future suggestions, feature requests, etc. you can find some [guidance on where to log them here](https://geocat.ucar.edu/pages/support.html). However, this would potentially be a nice addition to [geocat-comp](https://github.com/NCAR/geocat-comp).).  We also have a [Google Form for feature requests](https://docs.google.com/forms/d/e/1FAIpQLSeWuogl8Z671et3DdrmglenBPKGFmHVHkpSamTQeoPGuytLZw/viewform), if you prefer that format.

I'm not sure why there isn't more clear messaging on this repository about the current status, but I'll see what I can do about that as well.

**Comment by adriantompkins** [comment]
Apologies, I was not aware that pyngl was also in maintenance mode, I thought that was only ncl itself, and that ncl functionality was slowly being migrated to this python package. Thanks for the follow up and I'll take a look at geocat-comp

**Comment by kafitzgerald** [comment]
No problem at all.  The status should certainly be more clear.  

Thanks again for the feature request!
