### ISSUE TITLE
Maintenance mode messaging

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/pyngl#57]
Add clearer messaging on the current status of this project to the repository.  See #56.

**Comment by kafitzgerald** [comment]
This should also be more clear from the [documentation page](https://www.pyngl.ucar.edu/) for PyNIO and PyNGL.

**Comment by kafitzgerald** [comment]
Noting that the various repo READMEs have been updated, but we're still looking into updating the PyNGL / PyNIO website.

**Comment by phansel** [comment]
The announcement link (https://geocat.ucar.edu/blog/2020/11/11/November-2020-update) given is broken. The correct link is https://geocat.ucar.edu/news/november-2020-update/.
